# ~/.bash_profile

# Source bashrc
if [ -f ~/.bashrc ]; then
    . ~/.bashrc
fi

# Set environment variables
export EDITOR=vim
export VISUAL=vim
export LANG=en_US.UTF-8

# Added by Windsurf
export PATH="/Users/harishimmadi/.codeium/windsurf/bin:$PATH"
. "/Users/harishimmadi/.deno/env"
. "$HOME/.cargo/env"
